version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: age_of_carnath_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: age_of_carnath_db
    ports:
      - "5666:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
