import type { Metadata } from "next";
import "./globals.css";
import { EB_Garamond, Cinzel } from "next/font/google";

const fontFamily = Cinzel({
  weight: ["400", "500", "700"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          fontFamily.className +
          " bg-customGray p-[50px] flex justify-center min-h-screen"
        }
      >
        <div className="flex flex-col">
          <h1 className="text-3xl font-medium">Age of Carnath</h1>
          {children}
        </div>
      </body>
    </html>
  );
}
