import type { Metadata } from "next";
import "./globals.css";
import { EB_Garamond } from "next/font/google";
import NavBar from "@/components/Nav";

const fontFamily = EB_Garamond({
  weight: ["400", "500", "700"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          fontFamily.className + " bg-customGray p-[50px] h-screen min-h-screen"
        }
      >
        <NavBar />
        <h1 className="text-4xl font-medium text-center">Age of Carnath</h1>
        {children}
      </body>
    </html>
  );
}
